### ISSUE TITLE
Creating Plot with [0, 0.0, 1, 0.0, 2, 0.0, 3, 0.0] crashes during burn()

### ISSUE THREAD

**Issue by sndgeek** [jaraco/svg.charts#19]
[0, 0.0, 1, 0.0, 2, 0.0, 3, 0.0]
Traceback (most recent call last):
  File "./crash.py", line 36, in <module>
    graph.burn()
  File "/Library/Python/2.7/site-packages/svg/charts/graph.py", line 152, in burn
    self.calculate_graph_dimensions()
  File "/Library/Python/2.7/site-packages/svg/charts/graph.py", line 676, in calculate_graph_dimensions
    self.calculate_left_margin()
  File "/Library/Python/2.7/site-packages/svg/charts/plot.py", line 189, in calculate_left_margin
    super(Plot, self).calculate_left_margin()
  File "/Library/Python/2.7/site-packages/svg/charts/graph.py", line 187, in calculate_left_margin
    max_y_label_len = max(label_lengths)
ValueError: max() arg is an empty sequence

Best described by just running the attached file as a python script.  It's probably a particular combination of config settings and the data.
[crash.txt](https://github.com/jaraco/svg.charts/files/756066/crash.txt)

**Comment by jaraco** [comment]
I've incorporated a test that captures the failure you reported. It seems that if all of the y values are 0, the burn fails with the aforementioned error. Even if that individual failure is corrected, other failures happen because the y range is empty.

I welcome someone to dive in and devise a solution.

**Comment by jaraco** [comment]
I'd be interested to hear how other charting libraries handle this situation. What's a good numeric range for a dataset that has no vertical scale? Should it just put the range as [0, 1]?
