### ISSUE TITLE
Error on https://www.jaraco.com/charts/plot

### ISSUE THREAD

**Issue by danr** [jaraco/svg.charts#20]
```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/jaraco.com/lib/python3.5/site-packages/svg/charts/plot.py", line 150, in validate_data
    [len(x) for x in series]
  File "/opt/jaraco.com/lib/python3.5/site-packages/svg/charts/plot.py", line 150, in <listcomp>
    [len(x) for x in series]
TypeError: object of type 'int' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/jaraco.com/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/jaraco.com/lib/python3.5/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/jaraco.com/lib/python3.5/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/jaraco.com/lib/python3.5/site-packages/jaraco/site/__init__.py", line 47, in wrapper
    stream = func(*args, **kwargs)
  File "/opt/jaraco.com/lib/python3.5/site-packages/jaraco/site/charts.py", line 53, in plot
    title = 'series %d' % n,
  File "/opt/jaraco.com/lib/python3.5/site-packages/svg/charts/graph.py", line 111, in add_data
    self.validate_data(conf)
  File "/opt/jaraco.com/lib/python3.5/site-packages/svg/charts/plot.py", line 152, in validate_data
    self.validate_data_flat(series)
  File "/opt/jaraco.com/lib/python3.5/site-packages/svg/charts/plot.py", line 158, in validate_data_flat
    if len(series) % 2 != 0:
TypeError: object of type 'itertools.chain' has no len()
Powered by CherryPy 8.1.2
```

**Comment by jaraco** [comment]
Posting URL here for link - https://www.jaraco.com/charts/plot

**Comment by jaraco** [comment]
So I've updated the packages for the site and now for that URL, it's reporting a different error.

```
Traceback (most recent call last):
  File "/opt/jaraco.com/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/jaraco.com/lib/python3.5/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/jaraco.com/lib/python3.5/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/jaraco.com/lib/python3.5/site-packages/jaraco/site/__init__.py", line 47, in wrapper
    stream = func(*args, **kwargs)
  File "/opt/jaraco.com/lib/python3.5/site-packages/jaraco/site/charts.py", line 55, in plot
    res = XML(g.burn())
  File "/opt/jaraco.com/lib/python3.5/site-packages/genshi/input.py", line 275, in XML
    return Stream(list(XMLParser(StringIO(text))))
TypeError: initial_value must be str or None, not bytes
```

I think now the issue is that after porting to Python 3, `g.burn()` is returning bytes and not text. It should probably be text.

**Comment by jaraco** [comment]
I've decided that the rendering to bytes was a bad design and so updated the design to burn the XML to text. This change required a backward-incompatible release 4.0, but now the endpoint works.
